require "options"
require "keymaps"
require "plugins"
require "coc"
require "colorscheme"
require "cmp"
require "treesitter"
-- require "autopairs"
require "comment"
require "gitsigns"
require "nvim-tree"
require "bufferline"
require "lualine"
require "toggleterm"
require "project"
require "impatient"
require "indentline"
require "alpha"
require "whichkey"
require "autocommands"
require "asynctask"
require "ag"

vim.api.nvim_exec(
[[source ~/.config/nvim/lua/coc.vim]],
false)
